version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"